version: 2

jobs:
  build:
    machine:
      docker_layer_caching: false
    working_directory: ~/codeclimate/codeclimate-gofmt
    steps:
      - checkout
      - run: make image

  release_images:
    machine:
      docker_layer_caching: false
    working_directory: ~/codeclimate/codeclimate-gofmt
    steps:
      - checkout
      - run:
          name: Validate owner
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" -ne "codeclimate" ]
            then
              echo "Skipping release for non-codeclimate branches"
              circleci step halt
            fi
      - run: make image
      - run: echo "$GCLOUD_JSON_KEY_BASE64" | docker login -u _json_key --password-stdin us.gcr.io
      - run:
          name: Push image to GCR
          command: |
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              us.gcr.io/code-climate/codeclimate-gofmt:b$CIRCLE_BUILD_NUM
            docker push us.gcr.io/code-climate/codeclimate-gofmt:b$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - release_images:
          requires:
            - build
          filters:
            branches:
              only: /master|channel\/[\w-]+/
notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
